steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/finalproject-456519/sentiment-api", "."]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "sentiment-service",
        "--image",
        "gcr.io/finalproject-456519/sentiment-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - "gcr.io/finalproject-456519/sentiment-api"
